spring:
  application:
    name: Library Management System

  app:
    JWT_ACCESS_SECRET_KEY: mySecretKeyspkmndfsopkvajoirjgfpfngmoknmaccessToken
    JWT_REFRESH_SECRET_KEY: mySe12738aopsgjnspderewtekmndfsopkvajoirjg9438357437348763refreshToken
    jwtExpirationMs: 1200000
    jwtRefreshExpirationMs: 3600000

#  profiles:
#    active: dev  # Development Mode

  #jdbc:mysql://localhost:3306/social_network?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/librarymanagement
    username: root
    password: admin@123

  jpa:
    hibernate:
      ddl-auto: create-drop

#  servlet:
#    multipart:
#      enabled: true  # Enable multipart uploads
#      file-size-threshold: 2KB  # Threshold after which files are written to disk
#      max-file-size: 200MB  # Max file size
#      max-request-size: 215MB  # Max request size

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 50
      shutdown:
        await-termination: true
        await-termination-period: 60s

  mail:
    host: smtp.gmail.com
    port: 587
    username: mahitosh.runtime@gmail.com
    password: zorfqhzdulxxtprs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  swagger-ui:
    enabled: true  # Enable Swagger UI
    path: /swagger-ui.html  # URL path to access Swagger UI
  api-docs:
    enabled: true  # Enable API documentation
    path: /v3/api-docs  # Default path for OpenAPI JSON
  show-actuator: true  # (Optional) Show actuator endpoints in Swagger
#  packages-to-scan: com.yourpackage.controller  # (Optional) Restrict to specific package
#  paths-to-match: "/api/**"  # (Optional) Define API paths to include in documentation

cloudinary:
  cloud_name: dvxef5plb
  api_key: 272592496495854
  api_secret: KiAp22_2sT7GZ2AqZHcQEYkTZjE

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.type.descriptor: DEBUG
    org.springframework.web: INFO
    com.example.librarymanagement: DEBUG
  file:
    name: logs/application.log



# File Storage Properties
file:
  upload-dir: ./uploads

# Actuator Properties
management:
  endpoints:
    web:
      exposure:
        include: "*"


FRONTEND_URL: "http://localhost:4200,https://your-production-site.com"
FORGET_PASSWORD_URL: "http://localhost:4200"
server:
  port: 5001

