spring:
  application:
    name: Library Management System

  app:
    JWT_ACCESS_SECRET_KEY: mySuperSecretKey
    JWT_REFRESH_SECRET_KEY: mySuperSecretKeyeeeesdfete
    jwtExpirationMs: 120000
    jwtRefreshExpirationMs: 360000

#  profiles:
#    active: prod  # Production Mode

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://prod-db-server:3306/librarymanagement
    username: prod_user
    password: prod_secure_password

  jpa:
    hibernate:
      ddl-auto: validate  # Prevents accidental schema modifications

  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 50
      shutdown:
        await-termination: true
        await-termination-period: 60s

springdoc:
  swagger-ui:
    enabled: false  # Disable Swagger UI in Production
  api-docs:
    enabled: false  # Disable API documentation
  show-actuator: false

cloudinary:
  cloud_name: dvxef5plb
  api_key: 272592496495854
  api_secret: KiAp22_2sT7GZ2AqZHcQEYkTZjE

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.example.librarymanagement: INFO
  file:
    name: /var/logs/library-management.log

file:
  upload-dir: /var/uploads  # Production file storage

management:
  endpoints:
    web:
      exposure:
        include: "health,info"  # Limit exposed actuator endpoints

FRONTEND_URL: "https://your-production-site.com"

server:
  port: 5000
